#!/usr/bin/with-contenv bash

if [[ "$VERBOSE" = "yes" ]]; then
    set -x
fi

# Create directories
mkdir -p /var/lib/cassandra/data /var/lib/cassandra/commitlog /var/lib/cassandra/saved_caches
chown -R cassandra:cassandra /var/lib/cassandra


EC2_IP="$(curl -s --connect-timeout 5 http://169.254.169.254/latest/meta-data/local-ipv4)"
if [ -n "${EC2_IP}" ]; then
  echo -n "${EC2_IP}" > /var/run/s6/container_environment/EC2_IP
  test -n "${CONSUL_HTTP_ADDR}" || echo -n "${EC2_IP}:${CONSUL_HTTP_PORT:-8500}" > /var/run/s6/container_environment/CONSUL_HTTP_ADDR
fi

# Cassandra Default Configuration
: ${CASSANDRA_RPC_ADDRESS='0.0.0.0'}

: ${CASSANDRA_LISTEN_ADDRESS='auto'}
if [ "$CASSANDRA_LISTEN_ADDRESS" = 'auto' ]; then
  # Set the Host IP (EC2 private ip)
  test -n "${EC2_IP}" && CASSANDRA_LISTEN_ADDRESS="${EC2_IP}" || CASSANDRA_LISTEN_ADDRESS="$(hostname --ip-address)"
fi

: ${CASSANDRA_BROADCAST_ADDRESS="$CASSANDRA_LISTEN_ADDRESS"}

if [ "$CASSANDRA_BROADCAST_ADDRESS" = 'auto' ]; then
  # Set the Host IP (EC2 private ip)
  test -n "${EC2_IP}" && CASSANDRA_BROADCAST_ADDRESS="${EC2_IP}" || CASSANDRA_BROADCAST_ADDRESS="$(hostname --ip-address)"
fi
: ${CASSANDRA_BROADCAST_RPC_ADDRESS:=$CASSANDRA_BROADCAST_ADDRESS}

if [ -n "${CASSANDRA_NAME:+1}" ]; then
  : ${CASSANDRA_SEEDS:="cassandra"}
fi
: ${CASSANDRA_SEEDS:="$CASSANDRA_BROADCAST_ADDRESS"}

sed -ri 's/(- seeds:).*/\1 "'"$CASSANDRA_SEEDS"'"/' "${CASSANDRA_CONFIG}/cassandra.yaml"

for yaml in \
  broadcast_address \
  broadcast_rpc_address \
  cluster_name \
  endpoint_snitch \
  listen_address \
  num_tokens \
  rpc_address \
  start_rpc \
; do
  var="CASSANDRA_${yaml^^}"
  val="${!var}"
  if [ "$val" ]; then
    echo -n "${val}" > /var/run/s6/container_environment/${var}
    sed -ri 's/^(# )?('"$yaml"':).*/\2 '"$val"'/' "${CASSANDRA_CONFIG}/cassandra.yaml"
  fi
done

for rackdc in dc rack; do
  var="CASSANDRA_${rackdc^^}"
  val="${!var}"
  if [ "$val" ]; then
    echo -n "${val}" > /var/run/s6/container_environment/${var}
    sed -ri 's/^('"$rackdc"'=).*/\1 '"$val"'/' "${CASSANDRA_CONFIG}/cassandra-rackdc.properties"
  fi
done